name: ZMK Firmware

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 */2 *' # run every two months to keep artifacts from expiring

jobs:
  build:
    uses: ./.github/workflows/user_config_build.yaml
    # uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
